### ISSUE TITLE
Not all tests work with Python3

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfwinreg#54]
per @hillu in https://github.com/log2timeline/dfdatetime/issues/48

Running tests with Python3 produces a number of exceptions such as this one:
```
======================================================================
ERROR: testAtMaximumDepth (registry_searcher.FindSpecTest)
Tests the AtMaximumDepth function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/registry_searcher.py", line 103, in testAtMaximumDepth
    key_path=u'HKEY_CURRENT_USER\\Software\\Microsoft')
  File "./dfwinreg/registry_searcher.py", line 46, in __init__
    if len(key_path_arguments) > 1:
TypeError: object of type 'filter' has no len()
```
... and this one:
```
======================================================================
FAIL: testSplitKeyPath (key_paths.KeyPathTest)
Tests the SplitKeyPath function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/key_paths.py", line 22, in testSplitKeyPath
    self.assertEqual(path_segments, expected_path_segments)
AssertionError: <filter object at 0x7f0a21bb17b8> != ['HKEY_CURRENT_USER', 'Software', 'Microsoft']
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfwinreg/issues/56
